global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['10.53.1.23:9090']  // TODO ip自己写
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['10.53.1.23:8899']  // TODO ip自己写
  - job_name: 'node'
    static_configs:
    - targets: ['10.53.1.23:9100']  // TODO ip自己写