version: '3.4'
services:
  mysql:
    image: mysql:5.7.35
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      #设置时区使用宿主机时区,防止时间少8小时
      - /etc/localtime:/etc/localtime:ro
      - ./data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
      - ./log:/var/log/mysql/
      - ./init:/docker-entrypoint-initdb.d/
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --default-time-zone='+8:00'
    networks:
      dongjian:
        ipv4_address: 172.18.0.101
networks:
  dongjian:
    external: true
